language: python

python:
  - '3.4'

before_install:
  - 'sudo apt-get update'

install:
  - 'sudo apt-get install git libffi-dev libssl-dev libxml2 libxslt1-dev python-virtualenv python3-dev'
  - 'pip install -r requirements.txt'

script:
  - 'python setup.py test'
