language: python
python:
  - '2.7'
before_install:
  - 'sudo apt-get update'
# command to install dependencies
install:
  - 'sudo apt-get install swig'
  - 'pip install -r requirements.txt'
# command to run tests
script:
  - 'python setup.py test'
